export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
export ANT_OPTS="-Xms256m -Xmx1024m -XX:MaxPermSize=256m"
export MAVEN_OPTS="$ANT_OPTS -Xdebug -Xrunjdwp:transport=dt_socket,address=7777,server=y,suspend=n"
export ANT_HOME="~/Documents/voldemort/3rdparty/apache-ant-1.7.0"
# export ANT_HOME="/usr/local/apache-ant-1.7.0"

# Add Homebrew `/usr/local/bin` and User `~/bin` to the `$PATH`
PATH=$HOME/bin:$PATH
PATH=$PATH:$(npm config --global get prefix)/bin
PATH=$PATH:$ANT_HOME/bin
PATH=$PATH:$(yarn global bin)

# Load the shell dotfiles, and then some:
# * ~/.path can be used to extend `$PATH`.
# * ~/.extra can be used for other settings you don’t want to commit.
for file in ~/dotfiles/bash/{path,bash_prompt,exports,aliases,functions,extra}; do
  [ -r "$file" ] && source "$file"
done
unset file

# bash completion.
if which brew > /dev/null && [ -f "$(brew --prefix)/etc/bash_completion" ]; then
    source "$(brew --prefix)/etc/bash_completion";
elif [ -f /etc/bash_completion ]; then
    source /etc/bash_completion;
fi;

# homebrew completion
if which brew > /dev/null; then
    source "$(brew --prefix)/etc/bash_completion.d/brew"
fi;

test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"
export GPG_TTY=$(tty)
